[project]
name = "dataday-16-12-25"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.2",
    "groq>=0.37.1",
    "lxml>=6.0.2",
    "tiktoken>=0.12.0",
]
